In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("train_data01.csv",encoding="latin1")
len(df)

20000

In [2]:
#DataFrame.sample(n=None, frac=None, replace=False, weights=None, random_state=None, axis=None)
df_1=df.sample(n=20000)

In [6]:
df[:500000].sample(n=20000).to_csv("data_until2015.csv",encoding="latin1")

In [2]:
df.head(10)

,id,title,body,accepted_answer_id,answer_count,comment_count,creation_date,favorite_count,post_type_id,score,tags,view_count
0,337,XML Processing in Python,<p>I am about to build a piece of a project th...,342.0,12,1,2008-08-02 03:35:56,8.0,1,69,<python><xml>,7484
1,469,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...,3040.0,4,0,2008-08-02 15:11:16,NaN,1,39,<python><macos><fonts><photoshop>,2580
2,502,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...,7090.0,3,0,2008-08-02 17:01:59,13.0,1,40,<python><windows><image><pdf>,13299
3,535,Continuous Integration System for a Python Cod...,<p>I am starting to work on a hobby project wi...,541.0,7,0,2008-08-02 18:43:55,13.0,1,54,<python><continuous-integration><extreme-progr...,8619
4,594,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...,595.0,3,1,2008-08-03 01:15:09,8.0,1,41,<python><sql><database><oracle><cx-oracle>,40442
5,683,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...,57833.0,8,0,2008-08-03 13:19:17,NaN,1,43,<python><arrays><iteration>,9551
6,742,Class views in Django,"<p><a href=""http://www.djangoproject.com/"" rel...",33957.0,9,0,2008-08-03 15:55:29,9.0,1,51,<python><django><views><oop>,13274
7,766,Python and MySQL,<p>I can get Python to work with Postgresql bu...,1619.0,6,0,2008-08-03 17:44:07,3.0,1,35,<python><mysql><postgresql><bpgsql>,2915
8,773,How do I use Python's itertools.groupby()?,<p>I haven't been able to find an understandab...,7286.0,12,0,2008-08-03 18:27:10,181.0,1,401,<python><iteration>,224831
9,972,Adding a Method to an Existing Object Instance,<p>I've read that it is possible to add a meth...,2982.0,17,0,2008-08-04 02:17:52,279.0,1,540,<python><oop><methods><monkeypatching>,190355

In [30]:
def get_tags(word):
    count=0
    for i in range(len(df)):
        if word in df["tags"].values[i]:
            count+=1
        else:
            continue
    return count
get_tags("python-3.x")

146659

In [ ]:
def get_avg_view(word):#get single word avg_view count
    avg=0
    len_avg=0
    for i in range(len(df)):
        if word in df["body"].values[i]:
            len_avg+=1
            avg+=df["view_count"].values[i]
        else:
            contiue
    if len_avg==0:
        return 0
    return(avg/len_avg)

In [18]:
def get_tags(word):
    count=0
    for i in range(len(df)):
        if word in df["tags"].values[i]:
            count+=1
        else:
            continue
    return count
get_tags("python-3.x")

146659

In [29]:
def get_tags(word):
    for i in range(len(df)):
        if word in df["tags"].values[i]:
            df["tags"].values[i]="<"+word+">"
        else:
            continue
    return 0
get_tags("python-2.7")

0

In [7]:
import re
def get_clean_words(text):
    result=[]
    result_fin=[]
    with open(text,encoding="utf-8")as key:
        for i in key:
            result.append(i)
    for i in range(len(result)):
        result_all=[]
        result_clean=re.findall("\".*?\"",result[i])
        for j in range(len(result_clean)):
            result_all.append(eval(result_clean[j]))
        result_fin.append(result_all)
    return result_fin
def get_clean_weight(text):
    num=[]
    all_num=[]
    with open(text,encoding="utf-8")as key_2:
        for i in key_2:
            num.append(i)
    for i in range(len(num)):
        all_num.append(re.findall("\..*?\*",num[i]))
    all_clean_num=[]
    for i in range(30):
        clean_num=[]
        for j in all_num[i]:
            j=j.strip(",")
            j=float(j.strip("*"))
            clean_num.append(j)
        clean_num=[i*(1/sum(clean_num)) for i in clean_num]
        all_clean_num.append(clean_num)
    len(all_clean_num[0])
    return all_clean_num

In [8]:
text="key_word_3.txt"
word=get_clean_words(text)
all_clean_num=get_clean_weight(text)

In [9]:
def get_avg_view(word):#get single word avg_view count
    avg=0
    len_avg=0
    for i in range(len(df)):
        if word in df["body"].values[i]:
            len_avg+=1
            avg+=df["view_count"].values[i]
        else:
            continue
    if len_avg==0:
        return 0
    return(avg/len_avg)

In [10]:
def topic_avg_view(word):
    topic_view=[]
    func = lambda x,y:x*y
    for i in range(len(word)):
        topic=[]
        for j in word[i]:
            topic.append(get_avg_view(j))
        topicViews=sum(map(func,topic,all_clean_num[i]))
        topic_view.append(topicViews)
    return topic_view

In [11]:
topic_avg_view(word)

[284.5469602679132,
 324.0920108694164,
 320.38878362202917,
 403.23698309418177,
 270.8841606009538,
 347.7577402383627,
 448.2244236666241,
 262.29148711060424,
 280.29129043846245,
 320.68586047121386,
 295.34823057985665,
 326.588878826222,
 316.3082116397793,
 286.3888350798965,
 340.8910142213143,
 353.71029260018753,
 323.05657066586963,
 327.3714856141502,
 345.65255021781104,
 282.23935519197994,
 346.03329466213137,
 357.75332357123216,
 319.97367858482625,
 308.7213631031209,
 317.1030614944986,
 320.26750938235955,
 329.3700342968348,
 295.20165518972334,
 324.1434048812858,
 297.86735636013356]

In [12]:
df=df.fillna(0)

In [13]:
def get_avg_favor(word):#get single word avg_favor count
    avg=0
    len_avg=0
    for i in range(len(df)):
        if word in df["body"].values[i]:
            len_avg+=1
            avg+=df["favorite_count"].values[i]
        else:
            continue
    if len_avg==0:
        return 0
    return(avg/len_avg)
def topic_favor(word):
    topic_favorite=[]
    func=lambda x,y:x*y
    for i in range(len(word)):
        topic=[]
        for j in word[i]:
            topic.append(get_avg_favor(j))
        topic_favorite_count=sum(map(func,topic,all_clean_num[i]))
        topic_favorite.append(topic_favorite_count)
    return topic_favorite
topic_favor(word)

[0.15370093534979834,
 0.1439455092214664,
 0.18042576112156525,
 0.19755625601687102,
 0.1469737534285789,
 0.1433830997381719,
 0.1940541587099371,
 0.13775730627132346,
 0.1587694513334065,
 0.15185068256936696,
 0.16707597441067654,
 0.15528161595142453,
 0.16290258611328573,
 0.16362518341110627,
 0.1721950415706888,
 0.17922000389990303,
 0.16310600793657787,
 0.17302418961059302,
 0.16854586662349447,
 0.16191563809842813,
 0.15551798876195932,
 0.15642912982605875,
 0.16967858496864383,
 0.1494826159969403,
 0.1569304203489308,
 0.16381003685937182,
 0.1933183325762469,
 0.1598162948705816,
 0.164149685359714,
 0.16710920367756354]

In [68]:
df.head(10)

,id,title,body,accepted_answer_id,answer_count,comment_count,creation_date,favorite_count,post_type_id,score,tags,view_count
0,337,XML Processing in Python,<p>I am about to build a piece of a project th...,342.0,12,1,2008-08-02 03:35:56,8.0,1,69,<python><xml>,7484
1,469,How can I find the full path to a font from it...,<p>I am using the Photoshop's javascript API t...,3040.0,4,0,2008-08-02 15:11:16,0.0,1,39,<python><macos><fonts><photoshop>,2580
2,502,Get a preview JPEG of a PDF on Windows?,<p>I have a cross-platform (Python) applicatio...,7090.0,3,0,2008-08-02 17:01:59,13.0,1,40,<python><windows><image><pdf>,13299
3,535,Continuous Integration System for a Python Cod...,<p>I am starting to work on a hobby project wi...,541.0,7,0,2008-08-02 18:43:55,13.0,1,54,<python><continuous-integration><extreme-progr...,8619
4,594,cx_Oracle: How do I iterate over a result set?,<p>There are several ways to iterate over a re...,595.0,3,1,2008-08-03 01:15:09,8.0,1,41,<python><sql><database><oracle><cx-oracle>,40442
5,683,Using 'in' to match an attribute of Python obj...,<p>I don't remember whether I was dreaming or ...,57833.0,8,0,2008-08-03 13:19:17,0.0,1,43,<python><arrays><iteration>,9551
6,742,Class views in Django,"<p><a href=""http://www.djangoproject.com/"" rel...",33957.0,9,0,2008-08-03 15:55:29,9.0,1,51,<python><django><views><oop>,13274
7,766,Python and MySQL,<p>I can get Python to work with Postgresql bu...,1619.0,6,0,2008-08-03 17:44:07,3.0,1,35,<python><mysql><postgresql><bpgsql>,2915
8,773,How do I use Python's itertools.groupby()?,<p>I haven't been able to find an understandab...,7286.0,12,0,2008-08-03 18:27:10,181.0,1,401,<python><iteration>,224831
9,972,Adding a Method to an Existing Object Instance,<p>I've read that it is possible to add a meth...,2982.0,17,0,2008-08-04 02:17:52,279.0,1,540,<python><oop><methods><monkeypatching>,190355

In [14]:
def get_avg_accepted(word):#get single word avg_favor count
    avg=0
    len_avg=0
    for i in range(len(df)):
        if word in df["body"].values[i]:
            len_avg+=1
            if df["accepted_answer_id"].values[i]!=0:
                avg+=1
        else:
            continue
    if len_avg==0:
        return 0
    return(avg/len_avg)
def topic_accepted(word):
    topic_accepted=[]
    func=lambda x,y:x*y
    for i in range(len(word)):
        topic=[]
        for j in word[i]:
            topic.append(get_avg_accepted(j))
        topic_favorite_count=sum(map(func,topic,all_clean_num[i]))
        topic_accepted.append(topic_favorite_count)
    return topic_accepted
topic_accepted(word)

[0.4312189771383722,
 0.4208294572880168,
 0.4395011272610458,
 0.4108312422074892,
 0.4215759529555552,
 0.41750430454943915,
 0.446724674469918,
 0.39139590194873564,
 0.45021753414202903,
 0.453116703836061,
 0.41432999558951844,
 0.41287959326852325,
 0.4013722533310365,
 0.47619613787217097,
 0.44186230457328224,
 0.42927455685502214,
 0.4013572749759513,
 0.4355052161450952,
 0.4204492237769303,
 0.4385180228975362,
 0.39486129433253897,
 0.4311682781593309,
 0.5164974783275786,
 0.4303351054501784,
 0.47151837344358494,
 0.43651384625830014,
 0.3963878607964201,
 0.4548245580273925,
 0.4479686768723814,
 0.4504190675592747]

In [18]:
def get_avg(word):
    avg=0
    len_avg=0
    for i in range(len(df)):
        if word in df["body"].values[i]:
            len_avg+=1
            avg+=df["score"].values[i]
        else:
            continue
    if len_avg==0:
        return 0
    return (avg/len_avg)
#get_avg("")
def get_avg_score(word):
    all_topic_avg=[]
    func = lambda x,y:x*y
    for i in range(len(word)):
        topic_avg=[]
        for j in  word[i]:
            topic_avg.append(get_avg(j))
        topic_avg_score=sum(map(func,topic_avg,all_clean_num[i]))
        #topic_avg_score=sum(topic_avg_score)
        all_topic_avg.append(topic_avg_score)
    return all_topic_avg
get_avg_score(word)

[0.5739712917603261,
 0.49829643795122086,
 0.639391596192161,
 0.7161467503844862,
 0.5681514193143643,
 0.5650345203538345,
 0.6322532934038622,
 0.5516516984322717,
 0.5476261511486711,
 0.551816878441754,
 0.5729199209145728,
 0.5940251981941521,
 0.5943964049544364,
 0.6058311270362676,
 0.5859643431490872,
 0.6655928542811161,
 0.5882182052274798,
 0.6077847373900308,
 0.6143301981641602,
 0.5684653494697108,
 0.5645134480355195,
 0.5737235043347597,
 0.6928214257870646,
 0.5705520991689914,
 0.6020768038261455,
 0.6170631868668753,
 0.6050768769865635,
 0.5909459959101453,
 0.5896608670257831,
 0.6115173458313304]